-- Insert destinations
INSERT INTO destination (name, country, continent, image_url, latitude, longitude) VALUES
('Eiffel Tower', 'France', 'Europe', 'https://example.com/eiffel-tower.jpg', 48.8584, 2.2945),
('Great Wall of China', 'China', 'Asia', 'https://example.com/great-wall.jpg', 40.4319, 116.5704),
('Statue of Liberty', 'USA', 'North America', 'https://example.com/statue-liberty.jpg', 40.6892, -74.0445),
('Tokyo Tower', 'Japan', 'Asia', 'https://example.com/tokyo-tower.jpg', 35.6586, 139.7454),
('Sydney Opera House', 'Australia', 'Oceania', 'https://example.com/sydney-opera.jpg', -33.8568, 151.2153),
('Machu Picchu', 'Peru', 'South America', 'https://example.com/machu-picchu.jpg', -13.1631, -72.5450),
('Pyramids of Giza', 'Egypt', 'Africa', 'https://example.com/pyramids.jpg', 29.9792, 31.1342),
('Colosseum', 'Italy', 'Europe', 'https://example.com/colosseum.jpg', 41.8902, 12.4922),
('Taj Mahal', 'India', 'Asia', 'https://example.com/taj-mahal.jpg', 27.1751, 78.0421),
('Christ the Redeemer', 'Brazil', 'South America', 'https://example.com/christ-redeemer.jpg', -22.9519, -43.2105),
('Big Ben', 'United Kingdom', 'Europe', 'https://example.com/big-ben.jpg', 51.5007, -0.1246),
('Burj Khalifa', 'UAE', 'Asia', 'https://example.com/burj-khalifa.jpg', 25.1972, 55.2744),
('Sagrada Familia', 'Spain', 'Europe', 'https://example.com/sagrada-familia.jpg', 41.4036, 2.1744),
('Petra', 'Jordan', 'Asia', 'https://example.com/petra.jpg', 30.3285, 35.4444),
('Angkor Wat', 'Cambodia', 'Asia', 'https://example.com/angkor-wat.jpg', 13.4125, 103.8660),
('Acropolis', 'Greece', 'Europe', 'https://example.com/acropolis.jpg', 37.9715, 23.7266),
('Mount Rushmore', 'USA', 'North America', 'https://example.com/mount-rushmore.jpg', 43.8791, -103.4591),
('Chichen Itza', 'Mexico', 'North America', 'https://example.com/chichen-itza.jpg', 20.6829, -88.5686),
('Hagia Sophia', 'Turkey', 'Asia', 'https://example.com/hagia-sophia.jpg', 41.0086, 28.9802),
('Forbidden City', 'China', 'Asia', 'https://example.com/forbidden-city.jpg', 39.9167, 116.3833);

-- Insert clues and fun facts for each destination
INSERT INTO destination_clues (destination_id, clue) VALUES
(1, 'I was built for the 1889 World''s Fair'),
(1, 'I am made of iron and stand 324 meters tall'),
(1, 'I am located in the ''City of Light'''),
(2, 'I am the longest wall in the world'),
(2, 'I was built to protect against invasions'),
(2, 'I am visible from space'),
(3, 'I was a gift from France to the United States'),
(3, 'I stand on Liberty Island in New York Harbor'),
(3, 'I hold a torch in my right hand'),
(4, 'I am a communications and observation tower'),
(4, 'I was inspired by the Eiffel Tower'),
(4, 'I am painted in international orange and white'),
(5, 'I am a multi-venue performing arts center'),
(5, 'My roof resembles shells or sails'),
(5, 'I am located on Bennelong Point'),
(6, 'I am an ancient Incan citadel'),
(6, 'I am located high in the Andes Mountains'),
(6, 'I was built in the 15th century'),
(7, 'I am the oldest of the Seven Wonders of the Ancient World'),
(7, 'I was built as tombs for pharaohs'),
(7, 'I am located on the Giza Plateau'),
(8, 'I am an ancient amphitheater'),
(8, 'I could hold up to 80,000 spectators'),
(8, 'I was used for gladiatorial contests'),
(9, 'I am a white marble mausoleum'),
(9, 'I was built by Emperor Shah Jahan'),
(9, 'I am considered a symbol of love'),
(10, 'I am an Art Deco statue of Jesus Christ'),
(10, 'I stand atop Corcovado mountain'),
(10, 'I am one of the New Seven Wonders of the World'),
(11, 'I am a famous clock tower'),
(11, 'I am part of the Palace of Westminster'),
(11, 'My bell weighs 13.7 tons'),
(12, 'I am the tallest building in the world'),
(12, 'I have 163 floors'),
(12, 'I am located in Dubai'),
(13, 'I am an unfinished Roman Catholic church'),
(13, 'I was designed by Antoni Gaudí'),
(13, 'My construction began in 1882'),
(14, 'I am an ancient city carved into rock'),
(14, 'I was the capital of the Nabataean Kingdom'),
(14, 'I am known as the ''Rose City'''),
(15, 'I am the largest religious monument in the world'),
(15, 'I was originally a Hindu temple'),
(15, 'I am located in Cambodia'),
(16, 'I am an ancient citadel'),
(16, 'I contain several ancient buildings'),
(16, 'I overlook the city of Athens'),
(17, 'I feature the faces of four U.S. presidents'),
(17, 'I am carved into the Black Hills'),
(17, 'I was completed in 1941'),
(18, 'I am a large pre-Columbian city'),
(18, 'I was built by the Maya civilization'),
(18, 'I contain the Temple of Kukulcan'),
(19, 'I was originally a Greek Orthodox church'),
(19, 'I later became a mosque'),
(19, 'I am now a museum'),
(20, 'I was the Chinese imperial palace'),
(20, 'I have 980 buildings'),
(20, 'I served as the home of emperors for 500 years');

INSERT INTO destination_facts (destination_id, fact) VALUES
(1, 'The Eiffel Tower was initially criticized by some of France''s leading artists and intellectuals'),
(1, 'During World War II, when Hitler visited Paris, the French cut the lift cables so Hitler would have to climb the steps'),
(1, 'The tower was originally intended to be dismantled after 20 years'),
(2, 'The Great Wall is not a single continuous wall but a series of walls and fortifications'),
(2, 'It took over 2,000 years to build the entire wall'),
(2, 'The wall is made of various materials including stone, brick, tamped earth, and wood'),
(3, 'The Statue of Liberty was a gift from France to celebrate the centennial of American independence'),
(3, 'The statue''s full name is ''Liberty Enlightening the World'''),
(3, 'The seven spikes on the crown represent the seven continents'),
(4, 'Tokyo Tower is 13 meters taller than the Eiffel Tower'),
(4, 'The tower is repainted every five years'),
(4, 'It was the tallest structure in Japan until 2012'),
(5, 'The Sydney Opera House was designed by Danish architect Jørn Utzon'),
(5, 'The roof is made of over 1 million tiles'),
(5, 'It hosts over 1,500 performances each year'),
(6, 'Machu Picchu was built without the use of mortar'),
(6, 'The site was abandoned during the Spanish Conquest'),
(6, 'It was rediscovered in 1911 by Hiram Bingham'),
(7, 'The Great Pyramid was the tallest man-made structure for over 3,800 years'),
(7, 'The pyramids were built by paid workers, not slaves'),
(7, 'The Great Pyramid contains about 2.3 million stone blocks'),
(8, 'The Colosseum could be flooded for mock naval battles'),
(8, 'It was used for entertainment for nearly 500 years'),
(8, 'The Colosseum was damaged by several earthquakes'),
(9, 'The Taj Mahal changes color depending on the time of day'),
(9, 'It took 22 years and 20,000 workers to build'),
(9, 'The complex includes a mosque and a guest house'),
(10, 'Christ the Redeemer was completed in 1931'),
(10, 'The statue is made of reinforced concrete and soapstone'),
(10, 'It was struck by lightning in 2008 and 2014'),
(11, 'Big Ben is actually the name of the bell, not the tower'),
(11, 'The tower leans slightly to the northwest'),
(11, 'The clock mechanism is accurate to within one second'),
(12, 'The Burj Khalifa has the world''s highest observation deck'),
(12, 'It has the world''s fastest elevators'),
(12, 'The building''s design was inspired by a desert flower'),
(13, 'The Sagrada Familia is expected to be completed in 2026'),
(13, 'Gaudí is buried in the crypt'),
(13, 'The church has 18 spires representing different religious figures'),
(14, 'Petra was lost to the Western world for centuries'),
(14, 'The city was rediscovered in 1812'),
(14, 'The Treasury building was used in ''Indiana Jones and the Last Crusade'''),
(15, 'Angkor Wat is featured on Cambodia''s national flag'),
(15, 'It was originally dedicated to the Hindu god Vishnu'),
(15, 'The temple complex covers over 400 acres'),
(16, 'The Acropolis was built in the 5th century BCE'),
(16, 'The Parthenon was originally a temple to Athena'),
(16, 'The site has been damaged by wars and pollution'),
(17, 'Mount Rushmore took 14 years to complete'),
(17, 'The faces are 60 feet high'),
(17, 'The original plan included the presidents'' bodies'),
(18, 'Chichen Itza means ''at the mouth of the well of the Itza'''),
(18, 'The site contains a large cenote'),
(18, 'The pyramid has 365 steps, one for each day of the year'),
(19, 'Hagia Sophia means ''Holy Wisdom'''),
(19, 'The dome collapsed and was rebuilt twice'),
(19, 'The building contains both Christian and Islamic elements'),
(20, 'The Forbidden City has 9,999 rooms'),
(20, 'It was the home of 24 emperors'),
(20, 'The complex is surrounded by a 52-meter-wide moat'); 